In [33]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing the dataset
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

#Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelEncoder_X = LabelEncoder()
X[:, 3] = labelEncoder_X.fit_transform(X[:, 3])

from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(), [3])],    # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'  
)

X = np.array(transformer.fit_transform(X)) 

X = X[:, 1:]

#splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

print X_test

[[1.0 0.0 66051.52 182645.56 118148.2]
 [0.0 0.0 100671.96 91790.61 249744.55]
 [1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 27892.92 84710.77 164470.71]
 [1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 1.0 61136.38 152701.92 88218.23]
 [1.0 0.0 73994.56 122782.75 303319.26]
 [1.0 0.0 142107.34 91391.77 366168.42]]
